# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=30)),
                ('SixMonthsRevenue', models.CharField(max_length=30)),
                ('OneYearRevenue', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersno', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30)),
            ],
        ),
    ]
