# Generated by Django 2.0.5 on 2019-08-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialcompaniesapp', '0002_remove_companysales_sixmonthsrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysales',
            name='TwoYearRevenue',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
